### ISSUE TITLE
Página de inicio Cifras destacadas

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/colecciones-biologicas-frontend#11]
Página de inicio	"Cifras destacadas. No va ""REGISTROS y PUBLICADORES""
El conteo debe ser ""ESPECÍMENES"" ""COLECCIONES ""PUBLICADORES"""

**Comment by johnfra797** [comment]
Listo

**Comment by iraidamercedes** [comment]
@RicardoOrtizG  por favor revisar si este issue ya está. ¡gracias!

**Comment by RicardoOrtizG** [comment]
Si, según issue #[19 ](https://github.com/SIB-Colombia/colecciones-biologicas-frontend/issues/19#issue-337984208) esto ya está resuelto

**Comment by iraidamercedes** [comment]
Se cierra issue entonces.
