### ISSUE TITLE
Página de inicio	Contenidos y diseño de páginas de Sobre este portal y condiciones de uso

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/colecciones-biologicas-frontend#13]
Página de inicio	Contenidos y diseño de páginas de Sobre este portal y condiciones de uso en este issue: https://github.com/SIB-Colombia/biological_collections_frontend/issues/6 -

**Comment by RicardoOrtizG** [comment]
Este issue esta resuelto, los contenidos estan presentes y se pueden visualizar. Hay un error referenciado en el issue de listas [#13](https://github.com/SIB-Colombia/listas-de-especies-frontend/issues/13#issuecomment-436737427) y además el filtro lateral al darle clic, resalta la sección anterior.
