### ISSUE TITLE
Imagen de fondo - Colecciones en línea

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/colecciones-biologicas-frontend#2]
Img: 
https://s3.amazonaws.com/sib-resources/images/colecciones+en+linea/jpg/fondo-cl1.jpg

Créditos: Felipe Villegas / Instituto Humboldt

Sin embargo, sería conveniente utilizar alguna de las imágenes de las colecciones biológicas del Instituto Humboldt y enlazarla, a través de los créditos, a la colección o al espécimen directamente.

**Comment by jag2kn** [comment]
Hecho
