### ISSUE TITLE
Acerca de y condiciones de uso

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/colecciones-biologicas-frontend#6]
Aquí están los mockups de las páginas Sobre este portal y Condiciones de Uso:
https://drive.google.com/file/d/1pYCY0W_QrAWosQqtydHd9S1ab3oHL4cs/view?usp=sharing

Condiciones de uso (Documento con textos y enlaces): 
https://docs.google.com/document/d/1vc_ioEJZvbKsOEqq7CTqwGKSOW-PWbOjQYDcvV-OnRY/edit?usp=sharing

Sobre Colecciones en Línea (Documento con textos y enlaces): 
https://docs.google.com/document/d/13eKGJtUuZvCTPiZPMEXgX0UKXIb8FakVXW05jMc_nAQ/edit?usp=sharing

**Comment by RicardoOrtizG** [comment]
Resuelto, en el Canal actual se ven algunas mejoras sobre lo que se muestra en los Mockups
