### ISSUE TITLE
ESPECÍMENES | TABLA | La paginación muestra el mismo número de página, aunque funcione no pasa de la página 10

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/colecciones-biologicas-frontend#74]
La paginación en la vista de tabla funciona, si hay cambio de las páginas pero al ver la numeración pareciera que siempre está en la página N 1.

Sin embargo,  solo va de la página 1 -10, no se puede avanzar de ese número de páginas

**Comment by iraidamercedes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CONSULTA | En colecciones biológicas, arreglar la paginación pues no pasa del número 10.](https://trello.com/c/fXJD5oi3/109-consulta-en-colecciones-biol%C3%B3gicas-arreglar-la-paginaci%C3%B3n-pues-no-pasa-del-n%C3%BAmero-10)
